=== adobe/aem-core-forms-components/bundles/af-core/src/test/resources/schema/0.11.0-Pre/adaptive-form-properties.schema.json
{
  "$id": "classpath:/schema/0.11.0-Pre/adaptive-form-properties.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "$defs": {
    "SingleEventHandler": {
      "type": "string",
      "format": "json-formula"
    },
    "EventHandler": {
      "oneOf": [
        {
          "$ref": "#/$defs/SingleEventHandler"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SingleEventHandler"
          }
        }
      ]
    }
  },
  "properties": {
    ":type": {
      "type": "string",
      "title": "A hint to the rendering engine for rendering custom components."
    },
    "altText": {
      "title": "For images an alternate string to be displayed in case image cannot be shown",
      "type": "string"
    },
    "autocomplete": {
      "title": "Provide assistance to the end users to autocomplete values saved during previous form filling sessions",
      "type": "string"
    },
    "constraintMessages": {
      "title": "An object containing the custom error messages to be shown to the end user on different constraint validation",
      "type": "object",
      "propertyNames": {
        "enum": [
          "type",
          "required",
          "minimum",
          "maximum",
          "minLength",
          "maxLength",
          "step",
          "format",
          "pattern",
          "minItems",
          "maxItems",
          "minOccur",
          "maxOccur",
          "maxFileSize",
          "accept",
          "uniqueItems",
          "enforceEnum",
          "validationExpression"
        ],
        "errorMessage": "${0} is not a valid constraintMessage"
      }
    },
    "dataFormat": {
      "type": "string",
      "title": "The format in which the value will be exported or submitted."
    },
    "dataRef": {
      "type": [
        "string",
        "null"
      ],
      "title": "The jsonpath of the data instance that is mapped to the field's value.",
      "description": "It will be defined relative to the parent's dataRef property except for the two conditions. * null signifying don't save the data of this field or panel. * jsonpath begining with \"$.\" signifying that the jsonpath is not relative to the parent's dataRef property.\nIf the parent's dataRef is set to \"none\", then it will be relative to the"
    },
    "default": {
      "title": "The value of the field when no value is provided by the end user or data model.",
      "description": "The type of this property should match the value of the `type` property defined in the Field. If not, then a type coercion will be tried and if that fails, the value will be set to null.",
      "oneOf": [
        {
          "type": [
            "string",
            "number",
            "boolean"
          ]
        },
        {
          "type": "array",
          "items": {
            "type": [
              "string",
              "number",
              "boolean"
            ]
          }
        }
      ]
    },
    "description": {
      "type": "string",
      "title": "Extra description to be shown to the user to aid in form filling experience. It can be rich text. Can be used as help text for a field or a top level description for a Panel"
    },
    "displayFormat": {
      "type": "string",
      "title": "The format in which the value will be displayed to the user on screen in the field.",
      "description": "The format in which the value will be displayed to the user on screen in the field. For example when using a currency field, the currency sign should be shown to the user."
    },
    "editFormat": {
      "type": "string",
      "title": "The format in which the value will be edited by the user.",
      "description": "The format in which the value will be edited by the user. For instance users in Germany would want to interchange decimal (.) and comma (,) when entering numerical values."
    },
    "emptyValue": {
      "type": [
        "string"
      ],
      "title": "The value when user has not entered any value in the field",
      "description": "Determines what value should be saved when user has not entered any value in the field. Can be one of\n   * null\n   * undefined\n   * \"\" (empty string) (only valid for dataType = string)",
      "enum": [
        "null",
        "undefined",
        ""
      ]
    },
    "enabled": {
      "type": "boolean",
      "title": "whether the field is enabled and takes part in rules, events etc. A disabled field can have calculations and custom events"
    },
    "enum": {
      "title": "A list of options to put restrictions on the possible values of the field",
      "description": "The type of values in the enum array must match the value of the `type` property defined in the field. For array type fields, the type of element in the In case the `type` property is not defined, then the type of elements in the enum becomes the value of the `type` property. If the value of the `type` property doesn't match with the type of values in the `enum` array, then a type coercion will be made to match the `type` property. If the coercion is not possible, then the value will be set to null",
      "type": "array",
      "items": {
        "type": [
          "string",
          "boolean",
          "number"
        ]
      },
      "uniqueItems": true
    },
    "enumNames": {
      "title": "A user friendly text to display for the possible options to be shown to the end user.",
      "description": "The length of enum and enumNames array must match. In case the length of enum is greator, then those will be used as display text for the user. If the length of enumNames is greator, those will be discarded.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "events": {
      "$id": "https://git.corp.adobe.com/pages/livecycle/af2-docs/schema/generated/adaptive-form-events.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Specify what operations to perform on certain user or custom events.",
      "description": "Events is a dictionary of eventName to the actions to perform. Whenever the event is dispatched the expressions defined on that event are evaluated. The return value of that expression is applied to the field. The return value of the expression can be either of\n  * null, literal or array: The value property of the field is set to the return value\n  * dictionary: The field json is merged with the returned dictionary\n  * empty dictionary: the field should not be modified.",
      "type": "object",
      "properties": {
        "click": {
          "$ref": "#/$defs/EventHandler"
        },
        "initialize": {
          "$ref": "#/$defs/EventHandler"
        },
        "focus": {
          "$ref": "#/$defs/EventHandler"
        },
        "blur": {
          "$ref": "#/$defs/EventHandler"
        },
        "change": {
          "$ref": "#/$defs/EventHandler"
        },
        "submit": {
          "$ref": "#/$defs/EventHandler"
        }
      },
      "propertyNames": {
        "anyOf": [
          {
            "enum": [
              "click",
              "initialize",
              "focus",
              "blur",
              "change",
              "submit"
            ]
          },
          {
            "pattern": "custom:[a-zA-Z0-9]+"
          }
        ],
        "errorMessage": "${0} is not a valid Event Name. It should be either click, initialize, focus, blur, change or a custom event"
      }
    },
    "fieldType": {
      "title": "Type of widget to show to the user for capturing the data",
      "description": "It must be one of the types from the list * text-input * number-input * date-input * file-input * drop-down * radio-group * plain-text * checkbox * button * plain-text * panel * multiline-input * panel * image",
      "enum": [
        "text-input",
        "number-input",
        "date-input",
        "file-input",
        "multiline-input",
        "drop-down",
        "radio-group",
        "checkbox-group",
        "checkbox",
        "switch",
        "plain-text",
        "button",
        "panel",
        "image"
      ]
    },
    "label": {
      "$id": "https://git.corp.adobe.com/pages/livecycle/af2-docs/schema/generated/adaptive-form-label.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "richText": {
          "type": "boolean",
          "default": false,
          "title": "If the value of the label is to be considered as rich text or plain text"
        },
        "visible": {
          "type": "boolean",
          "title": "If the field's visible property is false, this property is ignored.",
          "default": true
        },
        "value": {
          "type": "string",
          "title": "The content of the label. If the rich text property is set to true, the contents will be considered as Rich Text"
        }
      },
      "required": [
        "value"
      ]
    },
    "name": {
      "type": "string",
      "title": "Name of the element. It is also the key in the JSON data, if dataRef is not defined explicitly, that the form produces. If two fields/panels under a same panel have the same name, their values will be same"
    },
    "placeholder": {
      "type": "string",
      "title": "The placeholder to show on the widget."
    },
    "properties": {
      "title": "An object containing custom properties that can be modified via rules as well.",
      "type": "object"
    },
    "readOnly": {
      "type": "boolean",
      "title": "whether the field should be readOnly to author or not",
      "description": "Determines how an element is treated: 'readOnly=true' means it cannot be modified by user. It will participate in all the events."
    },
    "richText": {
      "type": "boolean",
      "description": "whether the content of the text to be treated as rich text or not"
    },
    "rules": {
      "type": "object",
      "title": "Rules that modify the property of the object dynamically",
      "description": "An author can dynamically change any property that is defined in the spec as modifiable. The rules are evaluated whenever the dependency changes. Apart from properties defined on the field, rules can have an extra key `value` which auto computes the value of the field",
      "additionalProperties": {
        "type": "string"
      },
      "propertyNames": {
        "not": {
          "enum": [
            "name",
            "default",
            "type",
            "fieldType",
            "items",
            "displayFormat",
            "editFormat",
            "rules",
            "events",
            "props"
          ]
        }
      },
      "examples": [
        {
          "rules": {
            "required": "$form.maritalStatus.value == 'married'"
          }
        },
        {
          "lastName": {
            "name": "lastName",
            "rules": {
              "value": "$form.firstName.value & ' ' & $form.lastName.value"
            }
          }
        }
      ]
    },
    "screenReaderText": {
      "type": "string",
      "title": "a string to indicate the text to be read by screen readers"
    },
    "tooltip": {
      "type": "string",
      "title": "Tooltip of the form element"
    },
    "visible": {
      "type": "boolean",
      "title": "whether the field should be visible to author or not"
    },
    "id": {
      "type": "string",
      "title": "unique identifier for a form element"
    },
    "items": {
      "title": "Fields/Panels inside a Panel",
      "description": "If the Fields inside a panel are repeatable then the items should be an array containing only 1 field",
      "type": "array",
      "errorMessage": {
        "oneOf": "Items must be an array with atleast 1 field"
      }
    }
  }
}

=== adobe/aem-core-forms-components/bundles/af-core/src/test/resources/form/panelcontainer/exporter-panelcontainer.json
{
  "id":"panelcontainer-94f9ea9e7d",
  "constraintMessages": {
    "accept": "There is an error in the field",
    "enforceEnum": "There is an error in the field",
    "maxFileSize": "There is an error in the field",
    "maxItems": "There is an error in the field",
    "minItems": "There is an error in the field",
    "required": "There is an error in the field",
    "step": "There is an error in the field",
    "type": "There is an error in the field",
    "uniqueItems": "There is an error in the field",
    "validationExpression": "There is an error in the field"
  },
  "description":"dependent names description",
  "tooltip":"dependent names tooltip",
  "fieldType":"panel",
  "name":"abc",
  "visible":true,
  "enabled":true,
  "items":[
    {
      "id":"textinput-6c994d85b4",
      "constraintMessages": {
        "accept": "There is an error in the field",
        "enforceEnum": "There is an error in the field",
        "format": "There is an error in the field",
        "maxFileSize": "There is an error in the field",
        "maxItems": "There is an error in the field",
        "maxLength": "There is an error in the field",
        "minItems": "There is an error in the field",
        "minLength": "There is an error in the field",
        "pattern": "There is an error in the field",
        "required": "There is an error in the field",
        "step": "There is an error in the field",
        "type": "There is an error in the field",
        "uniqueItems": "There is an error in the field",
        "validationExpression": "There is an error in the field"
      },
      "description":"dummy",
      "type":"string",
      "fieldType":"text-input",
      "required":false,
      "name":"abc",
      "visible":false,
      "enabled":true,
      "readOnly":false,
      "label":{
        "visible":true,
        "richText":false,
        "value":"def"
      },
      "properties": {
        "fd:dor":{
          "dorExclusion":false
        }
      },
      "events" : {
        "custom:setProperty" : ["$event.payload"]
      },
      ":type":"core/fd/components/form/textinput/v1/textinput"
    }
  ],
  "label":{
    "visible":true,
    "richText":false,
    "value":"dependent names"
  },
  "properties": {
    "afs:layout": {
      "tooltipVisible":false
    },
    "fd:dor": {
      "dorExclusion" : true,
      "dorExcludeTitle" : false,
      "dorExcludeDescription" : false,
      "breakBeforeText": "Following Previous",
      "breakAfterText": "Continue Filling Parent",
      "overflowText": "None",
      "dorNumCols": "3",
      "dorLayoutType": "columnar"
    }
  },
  "events" : {
    "custom:setProperty" : ["$event.payload"]
  },
  ":type":"core/fd/components/form/panelcontainer/v1/panelcontainer"
}

=== adobe/aem-core-forms-components/bundles/af-core/src/test/resources/form/panelcontainer/exporter-panelcontainer-customized.json
{
  "id":"panelcontainer-d7d0a241a4",
  "description":"dependent names description",
  "tooltip":"dependent names tooltip",
  "fieldType":"panel",
  "name":"abc",
  "visible": false,
  "enabled": false,
  "readOnly": true,
  "items":[
    {
      "id": "textinput-7505d0a80f",
      "fieldType": "text-input",
      "name": "abc",
      "visible": false,
      "description": "dummy",
      "type": "string",
      "label": {
        "visible": true,
        "value": "def"
      },
      "events": {
        "custom:setProperty": [
          "$event.payload"
        ]
      },
      "properties": {
        "fd:dor": {
          "dorExclusion": false
        },
        "fd:path": "/content/panelcontainer-customized/textinput"
      },
      ":type": "core/fd/components/form/textinput/v1/textinput"
    }
  ],
  "label": {
    "value": "dependent names"
  },
  "events": {
    "custom:setProperty": [
      "$event.payload"
    ]
  },
  "properties": {
    "afs:layout": {
      "tooltipVisible": false
    },
    "fd:dor": {
      "dorExclusion": true,
      "dorExcludeTitle": false,
      "dorExcludeDescription": false,
      "breakBeforeText": "Following Previous",
      "breakAfterText": "Continue Filling Parent",
      "overflowText": "None",
      "dorNumCols": "3",
      "dorLayoutType": "columnar"
    },
    "fd:path": "/content/panelcontainer-customized"
  },
  ":type": "core/fd/components/form/panelcontainer/v1/panelcontainer"
}

=== adobe/aem-core-forms-components/bundles/af-core/src/test/resources/form/image/exporter-image.json
{
  "id": "image-7cfd7f1fe4",
  "fieldType": "image",
  "name": "emptyImage",
  "events": {
    "custom:setProperty": [
      "$event.payload"
    ]
  },
  "properties": {
    "fd:path": "/content/image",
    "fd:repoPath": "/content/dam/formsanddocuments/abc.jpeg",
    "fd:dor": {
      "dorExclusion": false
    },
    "customProp": "customPropValue"
  },
  ":type": "core/fd/components/form/image/v1/image"
}

=== adobe/aem-core-forms-components/bundles/af-core/src/test/resources/form/panelcontainer/exporter-rules-panelcontainer.json
{
  "id":"panelcontainer-da2cf7dff5",
  "constraintMessages": {
    "accept": "There is an error in the field",
    "enforceEnum": "There is an error in the field",
    "maxFileSize": "There is an error in the field",
    "maxItems": "There is an error in the field",
    "minItems": "There is an error in the field",
    "required": "There is an error in the field",
    "step": "There is an error in the field",
    "type": "There is an error in the field",
    "uniqueItems": "There is an error in the field",
    "validationExpression": "There is an error in the field"
  },
  "description":"dependent names description",
  "tooltip":"dependent names tooltip",
  "fieldType":"panel",
  "name":"abc",
  "visible":true,
  "enabled":true,
  "items":[
    {
      "id":"textinput-2d7a7460fa",
      "constraintMessages": {
        "accept": "There is an error in the field",
        "enforceEnum": "There is an error in the field",
        "format": "There is an error in the field",
        "maxFileSize": "There is an error in the field",
        "maxItems": "There is an error in the field",
        "maxLength": "There is an error in the field",
        "minItems": "There is an error in the field",
        "minLength": "There is an error in the field",
        "pattern": "There is an error in the field",
        "required": "There is an error in the field",
        "step": "There is an error in the field",
        "type": "There is an error in the field",
        "uniqueItems": "There is an error in the field",
        "validationExpression": "There is an error in the field"
      },
      "description":"dummy",
      "type":"string",
      "fieldType":"text-input",
      "required":false,
      "name":"abc",
      "visible":false,
      "enabled":true,
      "readOnly":false,
      "label":{
        "richText":false,
        "visible":true,
        "value":"def"
      },
      "properties": {
        "fd:dor":{
          "dorExclusion":false
        }
      },
      "events" : {
        "custom:setProperty" : ["$event.payload"]
      },
      ":type":"core/fd/components/form/textinput/v1/textinput"
    }
  ],
  "label":{
    "richText":false,
    "visible":true,
    "value":"dependent names"
  },
  "events":{
    "custom:setProperty" : ["$event.payload"],
    "change":[
      "some expression 2"
    ]
  },
  "properties":{
    "afs:layout":{
      "tooltipVisible":false
    },
    "fd:dor": {
      "dorExclusion" : false,
      "dorExcludeTitle" : false,
      "dorExcludeDescription" : false
    }
  },
  "rules":{
    "visible":"some expression"
  },
  ":type":"core/fd/components/form/panelcontainer/v1/panelcontainer"
}

=== adobe/aem-core-forms-components/bundles/af-core/src/test/resources/form/titleV2/exporter-title-wrongtype.json
{
  "id": "title-4a1ad605c0",
  "fieldType": "plain-text",
  "properties": {
    "fd:dor": {
      "dorExclusion": false
    },
    "fd:path": "/content/title-wrongtype",
    "fd:htmlelementType": null
  },
  "events": {
    "custom:setProperty": [
      "$event.payload"
    ]
  },
  ":type": "core/fd/components/form/title/v2/title"
}

=== adobe/aem-core-forms-components/bundles/af-core/src/test/resources/form/panel/exporter-rules-panel.json
{
  "id":"panel-81f441fcab",
  "constraintMessages": {
    "accept": "There is an error in the field",
    "enforceEnum": "There is an error in the field",
    "maxFileSize": "There is an error in the field",
    "maxItems": "There is an error in the field",
    "minItems": "There is an error in the field",
    "required": "There is an error in the field",
    "step": "There is an error in the field",
    "type": "There is an error in the field",
    "uniqueItems": "There is an error in the field",
    "validationExpression": "There is an error in the field"
  },
  "description":"dependent names description",
  "tooltip":"dependent names tooltip",
  "fieldType":"panel",
  "name":"abc",
  "visible":true,
  "enabled":true,
  "items": [
    {
      "id":"textinput-bec585e910",
      "constraintMessages": {
        "accept": "There is an error in the field",
        "enforceEnum": "There is an error in the field",
        "format": "There is an error in the field",
        "maxFileSize": "There is an error in the field",
        "maxItems": "There is an error in the field",
        "maxLength": "There is an error in the field",
        "minItems": "There is an error in the field",
        "minLength": "There is an error in the field",
        "pattern": "There is an error in the field",
        "required": "There is an error in the field",
        "step": "There is an error in the field",
        "type": "There is an error in the field",
        "uniqueItems": "There is an error in the field",
        "validationExpression": "There is an error in the field"
      },
      "description":"dummy",
      "type":"string",
      "fieldType":"text-input",
      "required":false,
      "name":"abc",
      "visible":false,
      "enabled":true,
      "readOnly":false,
      "label":{
        "visible":true,
        "richText":false,
        "value":"def"
      },
      "events" : {
        "custom:setProperty" : ["$event.payload"]
      },
      "properties": {
        "fd:dor":{
          "dorExclusion":false
        }
      },
      ":type":"core/fd/components/form/textinput/v1/textinput"
    }
  ],
  "label":{
    "visible":true,
    "richText":false,
    "value":"dependent names"
  },
  "events":{
    "custom:setProperty" : ["$event.payload"],
    "change":[
      "some expression 2"
    ]
  },
  "properties":{
    "afs:layout":{
      "tooltipVisible":false
    }
  },
  "rules": {
    "visible":"some expression"
  },
  ":type":"core/fd/components/form/panel/v1/panel"
}
